[files]
extend-exclude = ["**/build_assets/**", "*.json"]

[type.locale]
extend-glob = ["**/locale.rs"]
check-file = false

[default.extend-words]
flate = "flate"
strat = "strat"

[default]
locale = "en-us"
