edition = "2024"
style_edition = "2024"
newline_style = "Unix"

ignore = [
    "steel-core/src/behavior/generated",
    "steel-core/src/entity/generated",
    "steel-registry/src/generated",
    "steel-utils/src/generated",
    "steel-worldgen/src/generated",
]
