#!/usr/bin/env bash
#
# Regenerates nix/minecraft-assets.json from the targeted Minecraft version in
# Cargo.toml.
#
# The Nix package build has no network access, so it cannot run the download that
# steel-utils/build/build.rs performs. Instead the server jar is fetched as a
# fixed-output derivation, which requires the url and content hash to be pinned
# ahead of time. This script derives both from [workspace.package].version so the
# pin cannot drift from the version Cargo actually builds against.
#
# Run this after bumping the "+mc" suffix in Cargo.toml. CI verifies the result is
# up to date.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CARGO_TOML="$SCRIPT_DIR/Cargo.toml"
OUTPUT_FILE="$SCRIPT_DIR/nix/minecraft-assets.json"
MANIFEST_URL="https://piston-meta.mojang.com/mc/game/version_manifest_v2.json"

for tool in curl jq nix; do
    if ! command -v "$tool" >/dev/null 2>&1; then
        echo "error: '$tool' is required but not installed" >&2
        exit 1
    fi
done

# [workspace.package].version, e.g. "0.15.2+mc26.2". Parsed rather than read with
# a TOML library because Nix's builtins.fromTOML cannot handle this file, and the
# generated JSON has to agree with what the flake sees.
cargo_version="$(
    awk '
        /^\[workspace\.package\]/ { in_section = 1; next }
        /^\[/                     { in_section = 0 }
        in_section && /^version[[:space:]]*=/ { print; exit }
    ' "$CARGO_TOML" | sed -E 's/.*"(.*)".*/\1/'
)"

if [[ -z "$cargo_version" ]]; then
    echo "error: could not read [workspace.package].version from $CARGO_TOML" >&2
    exit 1
fi

if [[ "$cargo_version" != *"+mc"* ]]; then
    echo "error: version '$cargo_version' has no '+mc' suffix" >&2
    exit 1
fi

minecraft_version="${cargo_version##*+mc}"
echo "Targeting Minecraft $minecraft_version (from $cargo_version)"

version_url="$(
    curl -fsSL "$MANIFEST_URL" \
        | jq -r --arg id "$minecraft_version" '.versions[] | select(.id == $id) | .url'
)"

if [[ -z "$version_url" ]]; then
    echo "error: Minecraft $minecraft_version not found in the version manifest" >&2
    exit 1
fi

server_url="$(curl -fsSL "$version_url" | jq -r '.downloads.server.url')"

if [[ -z "$server_url" || "$server_url" == "null" ]]; then
    echo "error: no server download listed for Minecraft $minecraft_version" >&2
    exit 1
fi

echo "Prefetching $server_url"
server_hash="$(nix store prefetch-file --json "$server_url" | jq -r '.hash')"

mkdir -p "$(dirname "$OUTPUT_FILE")"
jq -n \
    --arg version "$cargo_version" \
    --arg minecraftVersion "$minecraft_version" \
    --arg url "$server_url" \
    --arg hash "$server_hash" \
    '{
        _comment: "Generated by update-minecraft-assets.sh. Do not edit by hand.",
        version: $version,
        minecraftVersion: $minecraftVersion,
        serverJar: { url: $url, hash: $hash }
    }' > "$OUTPUT_FILE"

echo "Wrote $OUTPUT_FILE"
