[package]
name = "steel-birthday"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
steel-core.workspace = true
steel-protocol.workspace = true
rustc-hash.workspace = true
small-map.workspace = true # falls du FxSmallMap für Teams nutzen willst
uuid.workspace = true